services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    ports:
      - "9111:9111"
    environment:
      - APP_PORT=9111
      - HTACCESS_FILE=/com.docker.devenvironments.code/secrets
      - SECRET_KEY_FILE=/com.docker.devenvironments.code/secret.key
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: bind
      source: /Users/djh/.bash_profile
      target: /root/.bash_profile
