version: '3.8'
services:
  app:
    entrypoint:
      - sleep
      - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    ports:
      - "9000:9000"
    environment:
      - HTACCESS_FILE=/app/secrets
      - SECRET_KEY_FILE=/app/secret.key
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: "/Users/djh/work/src/github.com/djh00t/klingon_auth_proxy/secrets"
        target: /app/secrets
      - type: bind
        source: "/Users/djh/work/src/github.com/djh00t/klingon_auth_proxy/environment"
        target: /app/environment
