version: '3.8'
services:
  htaccess:
    entrypoint:
      - sleep
      - infinity
    image: docker/dev-environments-default:stable-1
    init: true
#    ports:
#      - "9111:80"
    environment:
      - HTACCESS_FILE=/app/secrets
      - SECRET_KEY_FILE=/app/secret.key
      - APP_PORT=80
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: "/Users/djh/work/src/github.com/djh00t/klingon_auth_proxy/secrets"
        target: /app/secrets
      - type: bind
        source: "/Users/djh/work/src/github.com/djh00t/klingon_auth_proxy/environment"
        target: /app/environment
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
