version: '3.8'

services:
  app:
    build: .
    ports:
      - "9111:9111"
    environment:
      - APP_PORT=9111
      - HTACCESS_FILE=/com.docker.devenvironments.code/secrets
      - SECRET_KEY_FILE=/com.docker.devenvironments.code/secret.key
    volumes:
      - /etc/nginx/passwords:/app/htpasswd:ro
