version: '3.8'

services:
  app:
    build: .
    ports:
      - "9111:9111"
    environment:
      - APP_PORT=9111
      - HTACCESS_FILE=/com.docker.devenvironments.code/secrets
      - SECRET_KEY_FILE=/com.docker.devenvironments.code/secret.key
    volumes:
    - type: bind
      source: /Users/djh/work/src/github.com/klingon_auth_proxy/secrets
      target: /app/secrets