version: '3.8'

services:
  app:
    build: .
    ports:
      - "9111:9111"
    environment:
      - HTACCESS_FILE=/app/secrets
      - SECRET_KEY_FILE=/app/secret.key
    volumes:
    - type: bind
      source: "${HOME}/work/src/github.com/djh00t/klingon_auth_proxy/secrets"
      target: /app/secrets
